- name: variables to print
  hosts: wed
  vars:
   COURSE: "Devops with AWS"
   DURATION: "120HR"
   TRAINER: "Sivskumar Reddy M"
  task:
  - name: print the informatin
    anasible.builtin.debug:
     msg: "Hi I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}" 