- name: varaibles from file
  hosts: web
  var_file:
  - vars.yaml
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}" 
