- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false # if you want to see info in cmp
  - name: TRAINER
    prompt: Please enter the trainer name
    private: false # not confidentail
  - name: DURATION
    prompt: Please enter the duration
    private: false
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"