- name: create ec2 and r53 using ansible
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-0252d6dc54b021b05"
    sg_id: "sg-0a11c388ca7cf57ff"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
    zone: sisira.online
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: 'ec2_instances'

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instances }}" 

  - name: create R53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item}}.{{ zone }}" #ex.mysql.sisira.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}" 

  - name: create R53 public record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item}}.{{ zone }}" #ex.frontend.sisira.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: ec2_instances.results.item == "frontend"